/**
 * © 2013 - 2024 Tinder, Inc., ALL RIGHTS RESERVED
 * Tinder Obsidian v10.11.0
 * Do not edit directly
 * Generated on Thu, 12 Sep 2024 22:10:43 GMT
 */

import UIKit

@available(iOS 17.0, *)
public protocol StyleManagerProtocol {
    // Base
    var transparent: UIColor? { get }
    var white: UIColor? { get }
    var black: UIColor? { get }
    var gray10: UIColor? { get }
    var gray15: UIColor? { get }
    var gray20: UIColor? { get }
    var gray30: UIColor? { get }
    var gray40: UIColor? { get }
    var gray50: UIColor? { get }
    var gray60: UIColor? { get }
    var gray70: UIColor? { get }
    var gray80: UIColor? { get }
    var gray90: UIColor? { get }
    var gray95: UIColor? { get }
    var gray05: UIColor? { get }
    var green10: UIColor? { get }
    var green15: UIColor? { get }
    var green20: UIColor? { get }
    var green30: UIColor? { get }
    var green40: UIColor? { get }
    var green50: UIColor? { get }
    var green60: UIColor? { get }
    var green70: UIColor? { get }
    var green80: UIColor? { get }
    var green90: UIColor? { get }
    var green95: UIColor? { get }
    var green05: UIColor? { get }
    var teal10: UIColor? { get }
    var teal15: UIColor? { get }
    var teal20: UIColor? { get }
    var teal30: UIColor? { get }
    var teal40: UIColor? { get }
    var teal50: UIColor? { get }
    var teal60: UIColor? { get }
    var teal70: UIColor? { get }
    var teal80: UIColor? { get }
    var teal90: UIColor? { get }
    var teal95: UIColor? { get }
    var teal05: UIColor? { get }
    var blue10: UIColor? { get }
    var blue15: UIColor? { get }
    var blue20: UIColor? { get }
    var blue30: UIColor? { get }
    var blue40: UIColor? { get }
    var blue50: UIColor? { get }
    var blue60: UIColor? { get }
    var blue70: UIColor? { get }
    var blue80: UIColor? { get }
    var blue90: UIColor? { get }
    var blue95: UIColor? { get }
    var blue05: UIColor? { get }
    var purple10: UIColor? { get }
    var purple15: UIColor? { get }
    var purple20: UIColor? { get }
    var purple30: UIColor? { get }
    var purple40: UIColor? { get }
    var purple50: UIColor? { get }
    var purple60: UIColor? { get }
    var purple70: UIColor? { get }
    var purple80: UIColor? { get }
    var purple90: UIColor? { get }
    var purple95: UIColor? { get }
    var purple05: UIColor? { get }
    var fuchsia10: UIColor? { get }
    var fuchsia15: UIColor? { get }
    var fuchsia20: UIColor? { get }
    var fuchsia30: UIColor? { get }
    var fuchsia40: UIColor? { get }
    var fuchsia50: UIColor? { get }
    var fuchsia60: UIColor? { get }
    var fuchsia70: UIColor? { get }
    var fuchsia80: UIColor? { get }
    var fuchsia90: UIColor? { get }
    var fuchsia95: UIColor? { get }
    var fuchsia05: UIColor? { get }
    var red10: UIColor? { get }
    var red15: UIColor? { get }
    var red20: UIColor? { get }
    var red30: UIColor? { get }
    var red40: UIColor? { get }
    var red50: UIColor? { get }
    var red60: UIColor? { get }
    var red70: UIColor? { get }
    var red80: UIColor? { get }
    var red90: UIColor? { get }
    var red95: UIColor? { get }
    var red05: UIColor? { get }
    var yellowOrange10: UIColor? { get }
    var yellowOrange15: UIColor? { get }
    var yellowOrange20: UIColor? { get }
    var yellowOrange30: UIColor? { get }
    var yellowOrange40: UIColor? { get }
    var yellowOrange50: UIColor? { get }
    var yellowOrange60: UIColor? { get }
    var yellowOrange70: UIColor? { get }
    var yellowOrange80: UIColor? { get }
    var yellowOrange90: UIColor? { get }
    var yellowOrange95: UIColor? { get }
    var yellowOrange05: UIColor? { get }
    var gold10: UIColor? { get }
    var gold15: UIColor? { get }
    var gold20: UIColor? { get }
    var gold30: UIColor? { get }
    var gold40: UIColor? { get }
    var gold50: UIColor? { get }
    var gold60: UIColor? { get }
    var gold70: UIColor? { get }
    var gold80: UIColor? { get }
    var gold90: UIColor? { get }
    var gold95: UIColor? { get }
    var gold05: UIColor? { get }
    var brandPrimary: UIColor? { get }
    var brandPrimaryA11y: UIColor? { get }
    var brandGradient0: UIColor? { get }
    var brandGradient1: UIColor? { get }
    var brandGradientStart: UIColor? { get }
    var brandGradientEnd: UIColor? { get }
    var brandSubtle0: UIColor? { get }
    var brandSubtle1: UIColor? { get }
    var brandSubtleOnDark0: UIColor? { get }
    var brandSubtleOnDark1: UIColor? { get }
    var thirdPartySpotifyPrimary: UIColor? { get }
    var thirdPartySpotifyPrimaryInverse: UIColor? { get }
    var thirdPartyNoonlightPrimary: UIColor? { get }
    var thirdPartyNoonlightSecondary: UIColor? { get }
    var thirdPartyFacebookPrimary: UIColor? { get }
    var thirdPartyLinePrimary: UIColor? { get }
    var thirdPartyLineA11y: UIColor? { get }
    var gamepadRewind0: UIColor? { get }
    var gamepadRewind1: UIColor? { get }
    var gamepadRewindOnDark0: UIColor? { get }
    var gamepadRewindOnDark1: UIColor? { get }
    var gamepadNope0: UIColor? { get }
    var gamepadNope1: UIColor? { get }
    var gamepadNopeOnDark0: UIColor? { get }
    var gamepadNopeOnDark1: UIColor? { get }
    var gamepadSuperLike0: UIColor? { get }
    var gamepadSuperLike1: UIColor? { get }
    var gamepadSuperLikeOnDark0: UIColor? { get }
    var gamepadSuperLikeOnDark1: UIColor? { get }
    var gamepadSuperLikeOnLight0: UIColor? { get }
    var gamepadSuperLikeOnLight1: UIColor? { get }
    var gamepadSuperLikeSubtle0: UIColor? { get }
    var gamepadSuperLikeSubtle1: UIColor? { get }
    var gamepadSuperLikeSubtleOnDark0: UIColor? { get }
    var gamepadSuperLikeSubtleOnDark1: UIColor? { get }
    var gamepadLike0: UIColor? { get }
    var gamepadLike1: UIColor? { get }
    var gamepadLikeOnDark0: UIColor? { get }
    var gamepadLikeOnDark1: UIColor? { get }
    var gamepadLikeOnLight0: UIColor? { get }
    var gamepadLikeOnLight1: UIColor? { get }
    var gamepadLikeSubtle0: UIColor? { get }
    var gamepadLikeSubtle1: UIColor? { get }
    var gamepadLikeSubtleOnDark0: UIColor? { get }
    var gamepadLikeSubtleOnDark1: UIColor? { get }
    var gamepadBoost0: UIColor? { get }
    var gamepadBoost1: UIColor? { get }
    var gamepadBoostOnDark0: UIColor? { get }
    var gamepadBoostOnDark1: UIColor? { get }
    var gamepadBoostSubtle0: UIColor? { get }
    var gamepadBoostSubtle1: UIColor? { get }
    var gamepadBoostSubtleOnDark0: UIColor? { get }
    var gamepadBoostSubtleOnDark1: UIColor? { get }
    var gamepadSuperBoost0: UIColor? { get }
    var gamepadSuperBoost1: UIColor? { get }
    var gamepadSuperBoostOnDark0: UIColor? { get }
    var gamepadSuperBoostOnDark1: UIColor? { get }
    var gamepadSuperBoostSubtle0: UIColor? { get }
    var gamepadSuperBoostSubtle1: UIColor? { get }
    var gamepadSuperBoostSubtleOnDark0: UIColor? { get }
    var gamepadSuperBoostSubtleOnDark1: UIColor? { get }
    var gamepadSparksRewind0: UIColor? { get }
    var gamepadSparksRewind1: UIColor? { get }
    var gamepadSparksNope0: UIColor? { get }
    var gamepadSparksNope1: UIColor? { get }
    var gamepadSparksSuperLike0: UIColor? { get }
    var gamepadSparksSuperLike1: UIColor? { get }
    var gamepadSparksLike0: UIColor? { get }
    var gamepadSparksLike1: UIColor? { get }
    var gamepadSparksBoost0: UIColor? { get }
    var gamepadSparksBoost1: UIColor? { get }
    var exploreAttributionGradient0: UIColor? { get }
    var exploreAttributionGradient1: UIColor? { get }
    var festivalModeGradient0: UIColor? { get }
    var festivalModeGradient1: UIColor? { get }
    var spotifyMusicModeGradient0: UIColor? { get }
    var spotifyMusicModeGradient1: UIColor? { get }
    var hotTakesGradient0: UIColor? { get }
    var hotTakesGradient1: UIColor? { get }
    var passionsGradient0: UIColor? { get }
    var passionsGradient1: UIColor? { get }
    var vibesGradient0: UIColor? { get }
    var vibesGradient5: UIColor? { get }
    var vibesGradient10: UIColor? { get }
    var revenueGold0: UIColor? { get }
    var revenueGold1: UIColor? { get }
    var revenueGoldShine0: UIColor? { get }
    var revenueGoldShine5: UIColor? { get }
    var revenueGoldShine10: UIColor? { get }
    var revenueGoldShineAnimation0: UIColor? { get }
    var revenueGoldShineAnimation125: UIColor? { get }
    var revenueGoldShineAnimation250: UIColor? { get }
    var revenueGoldShineAnimation375: UIColor? { get }
    var revenueGoldShineAnimation500: UIColor? { get }
    var revenueGoldShineAnimation625: UIColor? { get }
    var revenueGoldShineAnimation750: UIColor? { get }
    var revenueGoldShineAnimation875: UIColor? { get }
    var revenueGoldShineAnimation1000: UIColor? { get }
    var revenueGoldOnDark0: UIColor? { get }
    var revenueGoldOnDark1: UIColor? { get }
    var revenueGoldShineOnDark0: UIColor? { get }
    var revenueGoldShineOnDark5: UIColor? { get }
    var revenueGoldShineOnDark10: UIColor? { get }
    var revenueGoldShineAnimationOnDark0: UIColor? { get }
    var revenueGoldShineAnimationOnDark125: UIColor? { get }
    var revenueGoldShineAnimationOnDark250: UIColor? { get }
    var revenueGoldShineAnimationOnDark375: UIColor? { get }
    var revenueGoldShineAnimationOnDark500: UIColor? { get }
    var revenueGoldShineAnimationOnDark625: UIColor? { get }
    var revenueGoldShineAnimationOnDark750: UIColor? { get }
    var revenueGoldShineAnimationOnDark875: UIColor? { get }
    var revenueGoldShineAnimationOnDark1000: UIColor? { get }
    var revenueGoldSubtle0: UIColor? { get }
    var revenueGoldSubtle1: UIColor? { get }
    var revenueGoldSubtleOnDark0: UIColor? { get }
    var revenueGoldSubtleOnDark1: UIColor? { get }
    var revenuePlatinum0: UIColor? { get }
    var revenuePlatinum1: UIColor? { get }
    var revenuePlatinumShine0: UIColor? { get }
    var revenuePlatinumShine5: UIColor? { get }
    var revenuePlatinumShine10: UIColor? { get }
    var revenuePlatinumShineAnimation0: UIColor? { get }
    var revenuePlatinumShineAnimation125: UIColor? { get }
    var revenuePlatinumShineAnimation250: UIColor? { get }
    var revenuePlatinumShineAnimation375: UIColor? { get }
    var revenuePlatinumShineAnimation500: UIColor? { get }
    var revenuePlatinumShineAnimation625: UIColor? { get }
    var revenuePlatinumShineAnimation750: UIColor? { get }
    var revenuePlatinumShineAnimation875: UIColor? { get }
    var revenuePlatinumShineAnimation1000: UIColor? { get }
    var revenuePlatinumOnDark0: UIColor? { get }
    var revenuePlatinumOnDark1: UIColor? { get }
    var revenuePlatinumShineOnDark0: UIColor? { get }
    var revenuePlatinumShineOnDark5: UIColor? { get }
    var revenuePlatinumShineOnDark10: UIColor? { get }
    var revenuePlatinumShineAnimationOnDark0: UIColor? { get }
    var revenuePlatinumShineAnimationOnDark125: UIColor? { get }
    var revenuePlatinumShineAnimationOnDark250: UIColor? { get }
    var revenuePlatinumShineAnimationOnDark375: UIColor? { get }
    var revenuePlatinumShineAnimationOnDark500: UIColor? { get }
    var revenuePlatinumShineAnimationOnDark625: UIColor? { get }
    var revenuePlatinumShineAnimationOnDark750: UIColor? { get }
    var revenuePlatinumShineAnimationOnDark875: UIColor? { get }
    var revenuePlatinumShineAnimationOnDark1000: UIColor? { get }
    var revenuePlatinumSubtle0: UIColor? { get }
    var revenuePlatinumSubtle1: UIColor? { get }
    var revenuePlatinumSubtleOnDark0: UIColor? { get }
    var revenuePlatinumSubtleOnDark1: UIColor? { get }
    var revenuePlus0: UIColor? { get }
    var revenuePlus1: UIColor? { get }
    var revenuePlusOnDark0: UIColor? { get }
    var revenuePlusOnDark1: UIColor? { get }
    var revenuePlusSubtle0: UIColor? { get }
    var revenuePlusSubtle1: UIColor? { get }
    var revenuePlusSubtleOnDark0: UIColor? { get }
    var revenuePlusSubtleOnDark1: UIColor? { get }
    var vaultIndigo20: UIColor? { get }
    var vaultIndigo95: UIColor? { get }
    var vaultPrimary: UIColor? { get }
    var vaultPrimaryLight: UIColor? { get }
    var vaultGradient0: UIColor? { get }
    var vaultGradient5: UIColor? { get }
    var vaultGradient10: UIColor? { get }
    var vaultSubtleOnLight0: UIColor? { get }
    var vaultSubtleOnLight1: UIColor? { get }
    var vaultSubtleOnDark0: UIColor? { get }
    var vaultSubtleOnDark1: UIColor? { get }
    var matchExpirationPrimary: UIColor? { get }
    var matchExpirationSecondary: UIColor? { get }
    var matchExpirationPrimaryOnDark: UIColor? { get }
    var matchExpirationGradient0: UIColor? { get }
    var matchExpirationGradient1: UIColor? { get }
    var matchExpirationGradientOnDark0: UIColor? { get }
    var matchExpirationGradientOnDark1: UIColor? { get }
    var sparksBackgroundGradient0: UIColor? { get }
    var sparksBackgroundGradient1: UIColor? { get }
    var sparksBackgroundGradientDark0: UIColor? { get }
    var sparksBackgroundGradientDark1: UIColor? { get }
    var sparksMatchmakerAttribution0: UIColor? { get }
    var sparksMatchmakerAttribution1: UIColor? { get }
    var sparksGrayBlue15: UIColor? { get }
    var sparksGrayBlue30: UIColor? { get }
    var sparksGrayBlue80: UIColor? { get }
    var sparksGrayBlue90: UIColor? { get }
    var sparksYellow20: UIColor? { get }
    var sparksYellow30: UIColor? { get }
    var sparksOrange50: UIColor? { get }
    var sparksRed60: UIColor? { get }
    var sparksTeal20: UIColor? { get }
    var sparksBlue50: UIColor? { get }
    var sparksBlue70: UIColor? { get }
    var sparksGreen20: UIColor? { get }
    var sparksGreen30: UIColor? { get }
    var sparksGreen40: UIColor? { get }
    var sparksPurple60: UIColor? { get }
    var sparksPink45: UIColor? { get }
    var opacityBlack10: UIColor? { get }
    var opacityBlack15: UIColor? { get }
    var opacityBlack20: UIColor? { get }
    var opacityBlack30: UIColor? { get }
    var opacityBlack40: UIColor? { get }
    var opacityBlack50: UIColor? { get }
    var opacityBlack60: UIColor? { get }
    var opacityBlack70: UIColor? { get }
    var opacityBlack80: UIColor? { get }
    var opacityBlack90: UIColor? { get }
    var opacityBlack95: UIColor? { get }
    var opacityBlack05: UIColor? { get }
    var opacityWhite10: UIColor? { get }
    var opacityWhite15: UIColor? { get }
    var opacityWhite20: UIColor? { get }
    var opacityWhite30: UIColor? { get }
    var opacityWhite40: UIColor? { get }
    var opacityWhite50: UIColor? { get }
    var opacityWhite60: UIColor? { get }
    var opacityWhite70: UIColor? { get }
    var opacityWhite80: UIColor? { get }
    var opacityWhite90: UIColor? { get }
    var opacityWhite95: UIColor? { get }
    var opacityWhite05: UIColor? { get }
    

    // Component
    var backgroundBadgeBrandDefault: UIColor? { get }
    var backgroundBadgeNotificationInactive: UIColor? { get }
    var backgroundBadgeNotificationActive: UIColor? { get }
    var backgroundBadgeVerifiedDefault: UIColor? { get }
    var backgroundBadgeOnlineNowDefault: UIColor? { get }
    var iconBadgeVerified: UIColor? { get }
    var textBadgeNotificationDefault: UIColor? { get }
    var textBadgeNotificationInactive: UIColor? { get }
    var backgroundBannerDefault: UIColor? { get }
    var iconContainerBannerDefault0: UIColor? { get }
    var iconContainerBannerDefault1: UIColor? { get }
    var iconBannerDefault: UIColor? { get }
    var iconBannerDismiss: UIColor? { get }
    var textBannerHeading: UIColor? { get }
    var textBannerBody: UIColor? { get }
    var dividerBannerDefault: UIColor? { get }
    var backgroundBottomSheetDefault: UIColor? { get }
    var backgroundButtonPrimary0: UIColor? { get }
    var backgroundButtonPrimary1: UIColor? { get }
    var backgroundButtonPrimarySmall: UIColor? { get }
    var backgroundButtonPrimaryOverlay: UIColor? { get }
    var backgroundButtonNeutral: UIColor? { get }
    var backgroundButtonDisabled: UIColor? { get }
    var backgroundButtonElevated: UIColor? { get }
    var backgroundButtonSparksNeutral: UIColor? { get }
    var backgroundButtonSparksExpandProfile: UIColor? { get }
    var borderButtonSecondary: UIColor? { get }
    var borderButtonSecondaryOverlay: UIColor? { get }
    var borderButtonSparksExpandProfile: UIColor? { get }
    var borderButtonFocused: UIColor? { get }
    var borderButtonFocusedOverlay: UIColor? { get }
    var foregroundButtonPrimary: UIColor? { get }
    var foregroundButtonPrimaryOverlay: UIColor? { get }
    var foregroundButtonSecondary: UIColor? { get }
    var foregroundButtonSecondaryOverlay: UIColor? { get }
    var foregroundButtonTertiary: UIColor? { get }
    var foregroundButtonTertiaryOverlay: UIColor? { get }
    var foregroundButtonNeutral: UIColor? { get }
    var foregroundButtonDisabled: UIColor? { get }
    var foregroundButtonSparksExpandProfile: UIColor? { get }
    var interactiveButtonPrimary: UIColor? { get }
    var interactiveButtonSecondary: UIColor? { get }
    var interactiveButtonTertiary: UIColor? { get }
    var interactiveButtonNeutral: UIColor? { get }
    var backgroundCardSparksHighlightCommon10: UIColor? { get }
    var backgroundCardSparksHighlightCommon11: UIColor? { get }
    var backgroundCardSparksHighlightCommon20: UIColor? { get }
    var backgroundCardSparksHighlightCommon21: UIColor? { get }
    var backgroundCardSparksHighlightCommon30: UIColor? { get }
    var backgroundCardSparksHighlightCommon31: UIColor? { get }
    var backgroundCardSparksHighlightUncommon10: UIColor? { get }
    var backgroundCardSparksHighlightUncommon11: UIColor? { get }
    var backgroundCardSparksHighlightUncommon20: UIColor? { get }
    var backgroundCardSparksHighlightUncommon21: UIColor? { get }
    var backgroundCardSparksHighlightUncommon30: UIColor? { get }
    var backgroundCardSparksHighlightUncommon31: UIColor? { get }
    var backgroundCardSparksIcebreaker0: UIColor? { get }
    var backgroundCardSparksIcebreaker1: UIColor? { get }
    var backgroundCardSparksPrompt0: UIColor? { get }
    var backgroundCardSparksPrompt1: UIColor? { get }
    var backgroundCardSparksQuiz0: UIColor? { get }
    var backgroundCardSparksQuiz1: UIColor? { get }
    var borderCard: UIColor? { get }
    var overlayCard0: UIColor? { get }
    var overlayCard1: UIColor? { get }
    var overlaySubtleCard0: UIColor? { get }
    var overlaySubtleCard1: UIColor? { get }
    var backgroundChatBubbleSend: UIColor? { get }
    var backgroundChatBubbleReceive: UIColor? { get }
    var textChatBubbleSend: UIColor? { get }
    var textChatBubbleReceive: UIColor? { get }
    var backgroundCheckboxDisabled: UIColor? { get }
    var backgroundCheckboxSelectedEnabled: UIColor? { get }
    var borderCheckboxUnselectedEnabled: UIColor? { get }
    var borderCheckboxUnselectedDisabled: UIColor? { get }
    var borderCheckboxUnselectedError: UIColor? { get }
    var iconCheckboxSelectedEnabled: UIColor? { get }
    var iconCheckboxSelectedDisabled: UIColor? { get }
    var backgroundDatepickerSelected: UIColor? { get }
    var textDatepickerInactive: UIColor? { get }
    var textDatepickerActive: UIColor? { get }
    var iconFormDefault: UIColor? { get }
    var iconFormDisabled: UIColor? { get }
    var iconFormError: UIColor? { get }
    var iconFormSuccess: UIColor? { get }
    var textFormLabelDefault: UIColor? { get }
    var textFormHelpDefault: UIColor? { get }
    var textFormHelpSuccess: UIColor? { get }
    var textFormHelpError: UIColor? { get }
    var textFormHelpDisabled: UIColor? { get }
    var backgroundGamepadPrimaryDefault: UIColor? { get }
    var backgroundGamepadPrimaryDisabled: UIColor? { get }
    var backgroundGamepadPrimaryDisabledOnSuperLike: UIColor? { get }
    var backgroundGamepadSecondaryDefault: UIColor? { get }
    var backgroundGamepadSecondaryDisabled: UIColor? { get }
    var backgroundGamepadRewindPressed0: UIColor? { get }
    var backgroundGamepadRewindPressed1: UIColor? { get }
    var backgroundGamepadNopePressed0: UIColor? { get }
    var backgroundGamepadNopePressed1: UIColor? { get }
    var backgroundGamepadSuperLikePressed0: UIColor? { get }
    var backgroundGamepadSuperLikePressed1: UIColor? { get }
    var backgroundGamepadLikePressed0: UIColor? { get }
    var backgroundGamepadLikePressed1: UIColor? { get }
    var backgroundGamepadBoostPressed0: UIColor? { get }
    var backgroundGamepadBoostPressed1: UIColor? { get }
    var backgroundGamepadSparksRewindDefault: UIColor? { get }
    var backgroundGamepadSparksRewindPressed0: UIColor? { get }
    var backgroundGamepadSparksRewindPressed1: UIColor? { get }
    var backgroundGamepadSparksNopeDefault: UIColor? { get }
    var backgroundGamepadSparksNopePressed0: UIColor? { get }
    var backgroundGamepadSparksNopePressed1: UIColor? { get }
    var backgroundGamepadSparksSuperLikeDefault: UIColor? { get }
    var backgroundGamepadSparksSuperLikePressed0: UIColor? { get }
    var backgroundGamepadSparksSuperLikePressed1: UIColor? { get }
    var backgroundGamepadSparksLikeDefault: UIColor? { get }
    var backgroundGamepadSparksLikePressed0: UIColor? { get }
    var backgroundGamepadSparksLikePressed1: UIColor? { get }
    var backgroundGamepadSparksBoostDefault: UIColor? { get }
    var backgroundGamepadSparksBoostPressed0: UIColor? { get }
    var backgroundGamepadSparksBoostPressed1: UIColor? { get }
    var borderGamepadPrimaryDisabled: UIColor? { get }
    var borderGamepadPrimaryDisabledOnSuperLike: UIColor? { get }
    var borderGamepadSecondaryDisabled: UIColor? { get }
    var borderGamepadRewindDefault: UIColor? { get }
    var borderGamepadNopeDefault: UIColor? { get }
    var borderGamepadSuperLikeDefault: UIColor? { get }
    var borderGamepadSuperLikeActive: UIColor? { get }
    var borderGamepadSuperLikeDisabled: UIColor? { get }
    var borderGamepadLikeDefault: UIColor? { get }
    var borderGamepadBoostDefault: UIColor? { get }
    var borderGamepadSparksRewindDefault: UIColor? { get }
    var borderGamepadSparksNopeDefault: UIColor? { get }
    var borderGamepadSparksSuperLikeDefault: UIColor? { get }
    var borderGamepadSparksLikeDefault: UIColor? { get }
    var borderGamepadSparksBoostDefault: UIColor? { get }
    var iconGamepadPrimaryDisabled: UIColor? { get }
    var iconGamepadPrimaryDisabledOnSuperLike: UIColor? { get }
    var iconGamepadPrimaryPressed: UIColor? { get }
    var iconGamepadPrimaryRewindDefault0: UIColor? { get }
    var iconGamepadPrimaryRewindDefault1: UIColor? { get }
    var iconGamepadPrimaryNopeDefault0: UIColor? { get }
    var iconGamepadPrimaryNopeDefault1: UIColor? { get }
    var iconGamepadPrimarySuperLikeDefault0: UIColor? { get }
    var iconGamepadPrimarySuperLikeDefault1: UIColor? { get }
    var iconGamepadPrimarySuperLikeActive: UIColor? { get }
    var iconGamepadPrimarySuperLikeDisabled: UIColor? { get }
    var iconGamepadPrimaryLikeDefault0: UIColor? { get }
    var iconGamepadPrimaryLikeDefault1: UIColor? { get }
    var iconGamepadPrimaryBoostDefault0: UIColor? { get }
    var iconGamepadPrimaryBoostDefault1: UIColor? { get }
    var iconGamepadSecondaryDisabled: UIColor? { get }
    var iconGamepadSecondaryPressed: UIColor? { get }
    var iconGamepadSecondaryRewindDefault0: UIColor? { get }
    var iconGamepadSecondaryRewindDefault1: UIColor? { get }
    var iconGamepadSecondaryNopeDefault0: UIColor? { get }
    var iconGamepadSecondaryNopeDefault1: UIColor? { get }
    var iconGamepadSecondarySuperLikeDefault0: UIColor? { get }
    var iconGamepadSecondarySuperLikeDefault1: UIColor? { get }
    var iconGamepadSecondaryLikeDefault0: UIColor? { get }
    var iconGamepadSecondaryLikeDefault1: UIColor? { get }
    var iconGamepadSecondaryBoostDefault0: UIColor? { get }
    var iconGamepadSecondaryBoostDefault1: UIColor? { get }
    var iconGamepadSparksRewindDefault0: UIColor? { get }
    var iconGamepadSparksRewindDefault1: UIColor? { get }
    var iconGamepadSparksRewindActive: UIColor? { get }
    var iconGamepadSparksNopeDefault0: UIColor? { get }
    var iconGamepadSparksNopeDefault1: UIColor? { get }
    var iconGamepadSparksNopeActive: UIColor? { get }
    var iconGamepadSparksSuperLikeDefault0: UIColor? { get }
    var iconGamepadSparksSuperLikeDefault1: UIColor? { get }
    var iconGamepadSparksSuperLikeActive: UIColor? { get }
    var iconGamepadSparksSuperLikeDisabled: UIColor? { get }
    var iconGamepadSparksLikeDefault0: UIColor? { get }
    var iconGamepadSparksLikeDefault1: UIColor? { get }
    var iconGamepadSparksLikeActive: UIColor? { get }
    var iconGamepadSparksBoostDefault0: UIColor? { get }
    var iconGamepadSparksBoostDefault1: UIColor? { get }
    var iconGamepadSparksBoostActive: UIColor? { get }
    var labelGamepadPrimaryCountSuperLike: UIColor? { get }
    var labelGamepadPrimaryCountBoost: UIColor? { get }
    var labelGamepadSecondaryCountSuperLike: UIColor? { get }
    var labelGamepadSecondaryCountBoost: UIColor? { get }
    var backgroundIconButtonPrimary0: UIColor? { get }
    var backgroundIconButtonPrimary1: UIColor? { get }
    var backgroundIconButtonSecondary: UIColor? { get }
    var backgroundIconButtonDisabled: UIColor? { get }
    var backgroundIconButtonOverlayDefault: UIColor? { get }
    var backgroundIconButtonOverlayDisabled: UIColor? { get }
    var iconIconButtonPrimary: UIColor? { get }
    var iconIconButtonSecondary: UIColor? { get }
    var iconIconButtonDisabled: UIColor? { get }
    var iconIconButtonOverlayDefault: UIColor? { get }
    var iconIconButtonOverlayDisabled: UIColor? { get }
    var labelIconButtonPrimary: UIColor? { get }
    var labelIconButtonSecondary: UIColor? { get }
    var labelIconButtonDisabled: UIColor? { get }
    var labelIconButtonOverlayDefault: UIColor? { get }
    var labelIconButtonOverlayDisabled: UIColor? { get }
    var borderIconButtonPrimary: UIColor? { get }
    var borderIconButtonSecondary: UIColor? { get }
    var borderIconButtonDisabled: UIColor? { get }
    var interactiveIconButtonPrimary: UIColor? { get }
    var interactiveIconButtonSecondary: UIColor? { get }
    var interactiveIconButtonOverlay: UIColor? { get }
    var backgroundModalOverlayDefault: UIColor? { get }
    var backgroundModalOverlayRecs: UIColor? { get }
    var backgroundModalContainerDefault: UIColor? { get }
    var foregroundModalHeading: UIColor? { get }
    var foregroundModalBody: UIColor? { get }
    var foregroundModalIcon: UIColor? { get }
    var actionNavigationSecondaryDisabled: UIColor? { get }
    var iconNavigationPrimaryInactive: UIColor? { get }
    var iconNavigationPrimaryActive0: UIColor? { get }
    var iconNavigationPrimaryActive1: UIColor? { get }
    var iconNavigationSecondaryStart: UIColor? { get }
    var iconNavigationSecondaryEnd: UIColor? { get }
    var backgroundPassionsShared: UIColor? { get }
    var backgroundPassionsSharedRec0: UIColor? { get }
    var backgroundPassionsSharedRec1: UIColor? { get }
    var backgroundPassionsEdit: UIColor? { get }
    var backgroundPassionsInactiveOverlay: UIColor? { get }
    var backgroundPassionsSharedOverlay: UIColor? { get }
    var backgroundPassionsSparksSharedOverlay0: UIColor? { get }
    var backgroundPassionsSparksSharedOverlay1: UIColor? { get }
    var backgroundPassionsSparksInactiveOverlay: UIColor? { get }
    var backgroundPassionsSparksInactive: UIColor? { get }
    var borderPassionsActive: UIColor? { get }
    var borderPassionsInactive: UIColor? { get }
    var borderPassionsShared: UIColor? { get }
    var borderPassionsSharedOverlay: UIColor? { get }
    var textPassionsActive: UIColor? { get }
    var textPassionsInactive: UIColor? { get }
    var textPassionsShared: UIColor? { get }
    var textPassionsSharedRec: UIColor? { get }
    var textPassionsInactiveOverlay: UIColor? { get }
    var textPassionsSharedOverlay: UIColor? { get }
    var backgroundProgressInactive: UIColor? { get }
    var foregroundProgressActive0: UIColor? { get }
    var foregroundProgressActive1: UIColor? { get }
    var backgroundRadioSelectedEnabled: UIColor? { get }
    var backgroundRadioSelectedDisabled: UIColor? { get }
    var backgroundRadioUnselectedDisabled: UIColor? { get }
    var borderRadioSelectedEnabled: UIColor? { get }
    var borderRadioSelectedDisabled: UIColor? { get }
    var borderRadioUnselectedEnabled: UIColor? { get }
    var borderRadioUnselectedDisabled: UIColor? { get }
    var iconRadioSelectedEnabled: UIColor? { get }
    var iconRadioSelectedDisabled: UIColor? { get }
    var backgroundRecCardContentHidden: UIColor? { get }
    var backgroundRecCardBottomDefault: UIColor? { get }
    var backgroundRecCardBottomSuperLike: UIColor? { get }
    var borderRecCardContentHidden: UIColor? { get }
    var iconRecCardContentHidden: UIColor? { get }
    var subCardRecCardSparks: UIColor? { get }
    var swipeOverlayRecCardSparksLike0: UIColor? { get }
    var swipeOverlayRecCardSparksLike1: UIColor? { get }
    var swipeOverlayRecCardSparksNope0: UIColor? { get }
    var swipeOverlayRecCardSparksNope1: UIColor? { get }
    var swipeOverlayRecCardSparksSuperLike0: UIColor? { get }
    var swipeOverlayRecCardSparksSuperLike1: UIColor? { get }
    var textRecCardContentHidden: UIColor? { get }
    var overlayRecCardDefault0: UIColor? { get }
    var overlayRecCardDefault25: UIColor? { get }
    var overlayRecCardDefault50: UIColor? { get }
    var overlayRecCardDefault75: UIColor? { get }
    var overlayRecCardDefault100: UIColor? { get }
    var overlayRecCardSuperLike0: UIColor? { get }
    var overlayRecCardSuperLike25: UIColor? { get }
    var overlayRecCardSuperLike50: UIColor? { get }
    var overlayRecCardSuperLike75: UIColor? { get }
    var overlayRecCardSuperLike100: UIColor? { get }
    var overlayRecCardVault0: UIColor? { get }
    var overlayRecCardVault25: UIColor? { get }
    var overlayRecCardVault50: UIColor? { get }
    var overlayRecCardVault75: UIColor? { get }
    var overlayRecCardVault100: UIColor? { get }
    var overlayRecCardHighlight0: UIColor? { get }
    var overlayRecCardHighlight25: UIColor? { get }
    var overlayRecCardHighlight50: UIColor? { get }
    var overlayRecCardHighlight75: UIColor? { get }
    var overlayRecCardHighlight100: UIColor? { get }
    var overlayRecCardIntentA0: UIColor? { get }
    var overlayRecCardIntentA25: UIColor? { get }
    var overlayRecCardIntentA50: UIColor? { get }
    var overlayRecCardIntentA75: UIColor? { get }
    var overlayRecCardIntentA100: UIColor? { get }
    var overlayRecCardIntentB0: UIColor? { get }
    var overlayRecCardIntentB25: UIColor? { get }
    var overlayRecCardIntentB50: UIColor? { get }
    var overlayRecCardIntentB75: UIColor? { get }
    var overlayRecCardIntentB100: UIColor? { get }
    var overlayRecCardIntentC0: UIColor? { get }
    var overlayRecCardIntentC25: UIColor? { get }
    var overlayRecCardIntentC50: UIColor? { get }
    var overlayRecCardIntentC75: UIColor? { get }
    var overlayRecCardIntentC100: UIColor? { get }
    var overlayRecCardIntentD0: UIColor? { get }
    var overlayRecCardIntentD25: UIColor? { get }
    var overlayRecCardIntentD50: UIColor? { get }
    var overlayRecCardIntentD75: UIColor? { get }
    var overlayRecCardIntentD100: UIColor? { get }
    var overlayRecCardIntentE0: UIColor? { get }
    var overlayRecCardIntentE25: UIColor? { get }
    var overlayRecCardIntentE50: UIColor? { get }
    var overlayRecCardIntentE75: UIColor? { get }
    var overlayRecCardIntentE100: UIColor? { get }
    var overlayRecCardIntentF0: UIColor? { get }
    var overlayRecCardIntentF25: UIColor? { get }
    var overlayRecCardIntentF50: UIColor? { get }
    var overlayRecCardIntentF75: UIColor? { get }
    var overlayRecCardIntentF100: UIColor? { get }
    var overlayRecCardSparksSuperLike0: UIColor? { get }
    var overlayRecCardSparksSuperLike25: UIColor? { get }
    var overlayRecCardSparksSuperLike50: UIColor? { get }
    var overlayRecCardSparksSuperLike75: UIColor? { get }
    var overlayRecCardSparksSuperLike100: UIColor? { get }
    var backgroundSearchDefault: UIColor? { get }
    var cursorSearchInput: UIColor? { get }
    var iconSearchStart: UIColor? { get }
    var iconSearchEndAction: UIColor? { get }
    var textSearchPlaceholderInactive: UIColor? { get }
    var textSearchInputActive: UIColor? { get }
    var textSearchInputInactive: UIColor? { get }
    var iconSelectorSelectedEnabled: UIColor? { get }
    var iconSelectorSelectedDisabled: UIColor? { get }
    var backgroundSliderAltTrackEnabled: UIColor? { get }
    var backgroundSliderAltTrackDisabled: UIColor? { get }
    var backgroundSliderAltKnobEnabled: UIColor? { get }
    var backgroundSliderAltKnobDisabled: UIColor? { get }
    var backgroundSliderAltFillEnabled: UIColor? { get }
    var backgroundSliderAltFillDisabled: UIColor? { get }
    var backgroundSliderDefaultTrackEnabled: UIColor? { get }
    var backgroundSliderDefaultTrackDisabled: UIColor? { get }
    var backgroundSliderDefaultKnobEnabled: UIColor? { get }
    var backgroundSliderDefaultKnobDisabled: UIColor? { get }
    var backgroundSliderDefaultFillEnabled: UIColor? { get }
    var backgroundSliderDefaultFillDisabled: UIColor? { get }
    var borderSliderAltKnobEnabled: UIColor? { get }
    var borderSliderAltKnobDisabled: UIColor? { get }
    var borderSliderDefaultKnobEnabled: UIColor? { get }
    var borderSliderDefaultKnobDisabled: UIColor? { get }
    var backgroundSwitchAltTrackSelected: UIColor? { get }
    var backgroundSwitchAltTrackUnselected: UIColor? { get }
    var backgroundSwitchAltTrackDisabled: UIColor? { get }
    var backgroundSwitchAltKnobSelected: UIColor? { get }
    var backgroundSwitchAltKnobUnselected: UIColor? { get }
    var backgroundSwitchAltKnobDisabled: UIColor? { get }
    var backgroundSwitchDefaultTrackSelected: UIColor? { get }
    var backgroundSwitchDefaultTrackUnselected: UIColor? { get }
    var backgroundSwitchDefaultTrackDisabled: UIColor? { get }
    var backgroundSwitchDefaultKnobSelected: UIColor? { get }
    var backgroundSwitchDefaultKnobUnselected: UIColor? { get }
    var backgroundSwitchDefaultKnobDisabled: UIColor? { get }
    var borderSwitchAltTrackSelected: UIColor? { get }
    var borderSwitchAltTrackUnselected: UIColor? { get }
    var borderSwitchAltTrackDisabled: UIColor? { get }
    var borderSwitchAltKnobSelected: UIColor? { get }
    var borderSwitchAltKnobUnselected: UIColor? { get }
    var borderSwitchAltKnobDisabled: UIColor? { get }
    var borderSwitchDefaultTrackSelected: UIColor? { get }
    var borderSwitchDefaultTrackUnselected: UIColor? { get }
    var borderSwitchDefaultTrackDisabled: UIColor? { get }
    var borderSwitchDefaultKnobSelected: UIColor? { get }
    var borderSwitchDefaultKnobUnselected: UIColor? { get }
    var borderSwitchDefaultKnobDisabled: UIColor? { get }
    var iconSwitchAltSelected: UIColor? { get }
    var iconSwitchAltUnselected: UIColor? { get }
    var iconSwitchAltDisabled: UIColor? { get }
    var iconSwitchDefaultSelected: UIColor? { get }
    var iconSwitchDefaultUnselected: UIColor? { get }
    var iconSwitchDefaultDisabled: UIColor? { get }
    var backgroundTableRowDefault: UIColor? { get }
    var backgroundTableRowPressed: UIColor? { get }
    var backgroundTableRowHover: UIColor? { get }
    var dividerTableRowDefault: UIColor? { get }
    var dividerTableRowSparks: UIColor? { get }
    var backgroundTappyIndicatorActive: UIColor? { get }
    var backgroundTappyIndicatorInactive: UIColor? { get }
    var backgroundTappyIndicatorSparksActive: UIColor? { get }
    var backgroundTappyIndicatorSparksInactive: UIColor? { get }
    var backgroundTappyContainerDefault: UIColor? { get }
    var backgroundTappySparks: UIColor? { get }
    var borderTappyIndicatorActive: UIColor? { get }
    var borderTappyIndicatorInactive: UIColor? { get }
    var borderTappyIndicatorSparksActive: UIColor? { get }
    var borderTappyIndicatorSparksInactive: UIColor? { get }
    var dividerTappySparks: UIColor? { get }
    var actionTextFieldQuietInactive: UIColor? { get }
    var actionTextFieldQuietActive: UIColor? { get }
    var actionTextFieldLoudInactive: UIColor? { get }
    var actionTextFieldLoudActive: UIColor? { get }
    var backgroundTextFieldQuietDefault: UIColor? { get }
    var backgroundTextFieldQuietHighlight: UIColor? { get }
    var backgroundTextFieldLoudDefault: UIColor? { get }
    var backgroundTextFieldLoudHighlight: UIColor? { get }
    var borderTextFieldQuietDefault: UIColor? { get }
    var borderTextFieldQuietError: UIColor? { get }
    var borderTextFieldQuietFocus: UIColor? { get }
    var borderTextFieldQuietDisabled: UIColor? { get }
    var borderTextFieldLoudDefault: UIColor? { get }
    var borderTextFieldLoudError: UIColor? { get }
    var borderTextFieldLoudFocus: UIColor? { get }
    var borderTextFieldLoudDisabled: UIColor? { get }
    var cursorTextFieldQuietDefault: UIColor? { get }
    var cursorTextFieldLoudDefault: UIColor? { get }
    var textTextFieldQuietCharactercountDefault: UIColor? { get }
    var textTextFieldLoudCharactercountDefault: UIColor? { get }
    var textTextFieldQuietLabelOptional: UIColor? { get }
    var textTextFieldQuietLabelError: UIColor? { get }
    var textTextFieldLoudLabelOptional: UIColor? { get }
    var textTextFieldLoudLabelError: UIColor? { get }
    var textTextFieldQuietPlaceholderDefault: UIColor? { get }
    var textTextFieldLoudPlaceholderDefault: UIColor? { get }
    var textTextFieldQuietInputDefault: UIColor? { get }
    var textTextFieldQuietInputDisabled: UIColor? { get }
    var textTextFieldLoudInputDefault: UIColor? { get }
    var textTextFieldLoudInputDisabled: UIColor? { get }
    var backgroundToastDefault: UIColor? { get }
    var backgroundTooltipDefault: UIColor? { get }
    var backgroundTooltipRevenueDefault: UIColor? { get }
    var backgroundTooltipTrustDefault: UIColor? { get }
    var borderTooltipDefault: UIColor? { get }
    var borderTooltipRevenueBoost: UIColor? { get }
    var borderTooltipRevenueNope: UIColor? { get }
    var borderTooltipRevenueLike: UIColor? { get }
    var borderTooltipRevenueSuperLike: UIColor? { get }
    var borderTooltipRevenueRewind: UIColor? { get }
    var iconTooltipDismiss: UIColor? { get }
    var textTooltipDefault: UIColor? { get }
    var textTooltipRevenueDefault: UIColor? { get }
    var textTooltipTrustDefault: UIColor? { get }
    

    // Invertible
    var invertibleWhite: UIColor? { get }
    var invertibleBlack: UIColor? { get }
    var invertibleGray10: UIColor? { get }
    var invertibleGray15: UIColor? { get }
    var invertibleGray20: UIColor? { get }
    var invertibleGray30: UIColor? { get }
    var invertibleGray40: UIColor? { get }
    var invertibleGray50: UIColor? { get }
    var invertibleGray60: UIColor? { get }
    var invertibleGray70: UIColor? { get }
    var invertibleGray80: UIColor? { get }
    var invertibleGray90: UIColor? { get }
    var invertibleGray95: UIColor? { get }
    var invertibleGray05: UIColor? { get }
    var invertibleGreen10: UIColor? { get }
    var invertibleGreen15: UIColor? { get }
    var invertibleGreen20: UIColor? { get }
    var invertibleGreen30: UIColor? { get }
    var invertibleGreen40: UIColor? { get }
    var invertibleGreen50: UIColor? { get }
    var invertibleGreen60: UIColor? { get }
    var invertibleGreen70: UIColor? { get }
    var invertibleGreen80: UIColor? { get }
    var invertibleGreen90: UIColor? { get }
    var invertibleGreen95: UIColor? { get }
    var invertibleGreen05: UIColor? { get }
    var invertibleTeal10: UIColor? { get }
    var invertibleTeal15: UIColor? { get }
    var invertibleTeal20: UIColor? { get }
    var invertibleTeal30: UIColor? { get }
    var invertibleTeal40: UIColor? { get }
    var invertibleTeal50: UIColor? { get }
    var invertibleTeal60: UIColor? { get }
    var invertibleTeal70: UIColor? { get }
    var invertibleTeal80: UIColor? { get }
    var invertibleTeal90: UIColor? { get }
    var invertibleTeal95: UIColor? { get }
    var invertibleTeal05: UIColor? { get }
    var invertibleBlue10: UIColor? { get }
    var invertibleBlue15: UIColor? { get }
    var invertibleBlue20: UIColor? { get }
    var invertibleBlue30: UIColor? { get }
    var invertibleBlue40: UIColor? { get }
    var invertibleBlue50: UIColor? { get }
    var invertibleBlue60: UIColor? { get }
    var invertibleBlue70: UIColor? { get }
    var invertibleBlue80: UIColor? { get }
    var invertibleBlue90: UIColor? { get }
    var invertibleBlue95: UIColor? { get }
    var invertibleBlue05: UIColor? { get }
    var invertiblePurple10: UIColor? { get }
    var invertiblePurple15: UIColor? { get }
    var invertiblePurple20: UIColor? { get }
    var invertiblePurple30: UIColor? { get }
    var invertiblePurple40: UIColor? { get }
    var invertiblePurple50: UIColor? { get }
    var invertiblePurple60: UIColor? { get }
    var invertiblePurple70: UIColor? { get }
    var invertiblePurple80: UIColor? { get }
    var invertiblePurple90: UIColor? { get }
    var invertiblePurple95: UIColor? { get }
    var invertiblePurple05: UIColor? { get }
    var invertibleFuchsia10: UIColor? { get }
    var invertibleFuchsia15: UIColor? { get }
    var invertibleFuchsia20: UIColor? { get }
    var invertibleFuchsia30: UIColor? { get }
    var invertibleFuchsia40: UIColor? { get }
    var invertibleFuchsia50: UIColor? { get }
    var invertibleFuchsia60: UIColor? { get }
    var invertibleFuchsia70: UIColor? { get }
    var invertibleFuchsia80: UIColor? { get }
    var invertibleFuchsia90: UIColor? { get }
    var invertibleFuchsia95: UIColor? { get }
    var invertibleFuchsia05: UIColor? { get }
    var invertibleRed10: UIColor? { get }
    var invertibleRed15: UIColor? { get }
    var invertibleRed20: UIColor? { get }
    var invertibleRed30: UIColor? { get }
    var invertibleRed40: UIColor? { get }
    var invertibleRed50: UIColor? { get }
    var invertibleRed60: UIColor? { get }
    var invertibleRed70: UIColor? { get }
    var invertibleRed80: UIColor? { get }
    var invertibleRed90: UIColor? { get }
    var invertibleRed95: UIColor? { get }
    var invertibleRed05: UIColor? { get }
    var invertibleYellowOrange10: UIColor? { get }
    var invertibleYellowOrange15: UIColor? { get }
    var invertibleYellowOrange20: UIColor? { get }
    var invertibleYellowOrange30: UIColor? { get }
    var invertibleYellowOrange40: UIColor? { get }
    var invertibleYellowOrange50: UIColor? { get }
    var invertibleYellowOrange60: UIColor? { get }
    var invertibleYellowOrange70: UIColor? { get }
    var invertibleYellowOrange80: UIColor? { get }
    var invertibleYellowOrange90: UIColor? { get }
    var invertibleYellowOrange95: UIColor? { get }
    var invertibleYellowOrange05: UIColor? { get }
    var invertibleGold10: UIColor? { get }
    var invertibleGold15: UIColor? { get }
    var invertibleGold20: UIColor? { get }
    var invertibleGold30: UIColor? { get }
    var invertibleGold40: UIColor? { get }
    var invertibleGold50: UIColor? { get }
    var invertibleGold60: UIColor? { get }
    var invertibleGold70: UIColor? { get }
    var invertibleGold80: UIColor? { get }
    var invertibleGold90: UIColor? { get }
    var invertibleGold95: UIColor? { get }
    var invertibleGold05: UIColor? { get }
    

    // Semantic
    var accentPrimary: UIColor? { get }
    var accentPrimaryGradient0: UIColor? { get }
    var accentPrimaryGradient1: UIColor? { get }
    var accentPrimaryA11y: UIColor? { get }
    var accentBrand: UIColor? { get }
    var accentBrandGradient0: UIColor? { get }
    var accentBrandGradient1: UIColor? { get }
    var accentLikeGradient0: UIColor? { get }
    var accentLikeGradient1: UIColor? { get }
    var accentSparksLikeGradient0: UIColor? { get }
    var accentSparksLikeGradient1: UIColor? { get }
    var accentLike: UIColor? { get }
    var accentNopeGradient0: UIColor? { get }
    var accentNopeGradient1: UIColor? { get }
    var accentSparksNopeGradient0: UIColor? { get }
    var accentSparksNopeGradient1: UIColor? { get }
    var accentNope: UIColor? { get }
    var accentSuperLikeGradient0: UIColor? { get }
    var accentSuperLikeGradient1: UIColor? { get }
    var accentSparksSuperLikeGradient0: UIColor? { get }
    var accentSparksSuperLikeGradient1: UIColor? { get }
    var accentSuperLike: UIColor? { get }
    var accentBoostGradient0: UIColor? { get }
    var accentBoostGradient1: UIColor? { get }
    var accentSparksBoostGradient0: UIColor? { get }
    var accentSparksBoostGradient1: UIColor? { get }
    var accentBoost: UIColor? { get }
    var accentRewindGradient0: UIColor? { get }
    var accentRewindGradient1: UIColor? { get }
    var accentSparksRewindGradient0: UIColor? { get }
    var accentSparksRewindGradient1: UIColor? { get }
    var accentRewind: UIColor? { get }
    var accentGoldGradient0: UIColor? { get }
    var accentGoldGradient1: UIColor? { get }
    var accentGoldShineGradient0: UIColor? { get }
    var accentGoldShineGradient5: UIColor? { get }
    var accentGoldShineGradient10: UIColor? { get }
    var accentGold: UIColor? { get }
    var accentPlatinumGradient0: UIColor? { get }
    var accentPlatinumGradient1: UIColor? { get }
    var accentPlatinumShineGradient0: UIColor? { get }
    var accentPlatinumShineGradient5: UIColor? { get }
    var accentPlatinumShineGradient10: UIColor? { get }
    var accentPlatinum: UIColor? { get }
    var accentPlatinumGradientInverse0: UIColor? { get }
    var accentPlatinumGradientInverse1: UIColor? { get }
    var accentPlatinumShineGradientInverse0: UIColor? { get }
    var accentPlatinumShineGradientInverse5: UIColor? { get }
    var accentPlatinumShineGradientInverse10: UIColor? { get }
    var accentSelectGradient0: UIColor? { get }
    var accentSelectGradient5: UIColor? { get }
    var accentSelectGradient10: UIColor? { get }
    var accentSelect: UIColor? { get }
    var accentError: UIColor? { get }
    var accentSuccess: UIColor? { get }
    var accentActive: UIColor? { get }
    var accentLink: UIColor? { get }
    var accentChat: UIColor? { get }
    var accentTrust: UIColor? { get }
    var accentBlue: UIColor? { get }
    var accentFuchsia: UIColor? { get }
    var accentGreen: UIColor? { get }
    var accentPurple: UIColor? { get }
    var accentRed: UIColor? { get }
    var accentTeal: UIColor? { get }
    var accentYellowOrange: UIColor? { get }
    var accentExploreGradient0: UIColor? { get }
    var accentExploreGradient1: UIColor? { get }
    var accentFestivalModeGradient0: UIColor? { get }
    var accentFestivalModeGradient1: UIColor? { get }
    var accentSpotifyMusicModeGradient0: UIColor? { get }
    var accentSpotifyMusicModeGradient1: UIColor? { get }
    var accentHotTakesGradient0: UIColor? { get }
    var accentHotTakesGradient1: UIColor? { get }
    var accentMatchExpirationGradient0: UIColor? { get }
    var accentMatchExpirationGradient1: UIColor? { get }
    var accentPassionsGradient0: UIColor? { get }
    var accentPassionsGradient1: UIColor? { get }
    var accentVibesGradient0: UIColor? { get }
    var accentVibesGradient5: UIColor? { get }
    var accentVibesGradient10: UIColor? { get }
    var accentMatchmakerGradient0: UIColor? { get }
    var accentMatchmakerGradient1: UIColor? { get }
    var actionActive: UIColor? { get }
    var actionInactive: UIColor? { get }
    var backgroundPrimary: UIColor? { get }
    var backgroundPrimaryInverse: UIColor? { get }
    var backgroundPrimaryLinear0: UIColor? { get }
    var backgroundPrimaryLinear1: UIColor? { get }
    var backgroundSecondary: UIColor? { get }
    var backgroundSecondaryInverse: UIColor? { get }
    var backgroundTertiary: UIColor? { get }
    var backgroundTertiaryInverse: UIColor? { get }
    var backgroundInactive: UIColor? { get }
    var backgroundPrimaryStaticLight: UIColor? { get }
    var backgroundPrimaryStaticDark: UIColor? { get }
    var backgroundSecondaryStaticLight: UIColor? { get }
    var backgroundSecondaryStaticDark: UIColor? { get }
    var backgroundOverlayPrimary: UIColor? { get }
    var backgroundOverlaySecondary: UIColor? { get }
    var backgroundBrand: UIColor? { get }
    var backgroundBrandGradient0: UIColor? { get }
    var backgroundBrandGradient1: UIColor? { get }
    var backgroundBrandSubtle0: UIColor? { get }
    var backgroundBrandSubtle1: UIColor? { get }
    var backgroundError: UIColor? { get }
    var backgroundRewind0: UIColor? { get }
    var backgroundRewind1: UIColor? { get }
    var backgroundRewindInverse0: UIColor? { get }
    var backgroundRewindInverse1: UIColor? { get }
    var backgroundNope0: UIColor? { get }
    var backgroundNope1: UIColor? { get }
    var backgroundNopeInverse0: UIColor? { get }
    var backgroundNopeInverse1: UIColor? { get }
    var backgroundSuperLike0: UIColor? { get }
    var backgroundSuperLike1: UIColor? { get }
    var backgroundSuperLikeInverse0: UIColor? { get }
    var backgroundSuperLikeInverse1: UIColor? { get }
    var backgroundSuperLikeSubtle0: UIColor? { get }
    var backgroundSuperLikeSubtle1: UIColor? { get }
    var backgroundLike0: UIColor? { get }
    var backgroundLike1: UIColor? { get }
    var backgroundLikeInverse0: UIColor? { get }
    var backgroundLikeInverse1: UIColor? { get }
    var backgroundLikeSubtle0: UIColor? { get }
    var backgroundLikeSubtle1: UIColor? { get }
    var backgroundBoost0: UIColor? { get }
    var backgroundBoost1: UIColor? { get }
    var backgroundBoostInverse0: UIColor? { get }
    var backgroundBoostInverse1: UIColor? { get }
    var backgroundBoostSubtle0: UIColor? { get }
    var backgroundBoostSubtle1: UIColor? { get }
    var backgroundSuperBoost0: UIColor? { get }
    var backgroundSuperBoost1: UIColor? { get }
    var backgroundSuperBoostInverse0: UIColor? { get }
    var backgroundSuperBoostInverse1: UIColor? { get }
    var backgroundSuperBoostSubtle0: UIColor? { get }
    var backgroundSuperBoostSubtle1: UIColor? { get }
    var backgroundPlusSubtle0: UIColor? { get }
    var backgroundPlusSubtle1: UIColor? { get }
    var backgroundDisabled: UIColor? { get }
    var backgroundGold0: UIColor? { get }
    var backgroundGold1: UIColor? { get }
    var backgroundGoldInverse0: UIColor? { get }
    var backgroundGoldInverse1: UIColor? { get }
    var backgroundGoldShine0: UIColor? { get }
    var backgroundGoldShine5: UIColor? { get }
    var backgroundGoldShine10: UIColor? { get }
    var backgroundGoldShineInverse0: UIColor? { get }
    var backgroundGoldShineInverse5: UIColor? { get }
    var backgroundGoldShineInverse10: UIColor? { get }
    var backgroundGoldSubtle0: UIColor? { get }
    var backgroundGoldSubtle1: UIColor? { get }
    var backgroundPlatinum0: UIColor? { get }
    var backgroundPlatinum1: UIColor? { get }
    var backgroundPlatinumInverse0: UIColor? { get }
    var backgroundPlatinumInverse1: UIColor? { get }
    var backgroundPlatinumShine0: UIColor? { get }
    var backgroundPlatinumShine5: UIColor? { get }
    var backgroundPlatinumShine10: UIColor? { get }
    var backgroundPlatinumShineInverse0: UIColor? { get }
    var backgroundPlatinumShineInverse5: UIColor? { get }
    var backgroundPlatinumShineInverse10: UIColor? { get }
    var backgroundPlatinumSubtle0: UIColor? { get }
    var backgroundPlatinumSubtle1: UIColor? { get }
    var backgroundScriptedOnboarding0: UIColor? { get }
    var backgroundScriptedOnboarding1: UIColor? { get }
    var backgroundSwipesurge0: UIColor? { get }
    var backgroundSwipesurge1: UIColor? { get }
    var backgroundReadReceiptsBadge: UIColor? { get }
    var backgroundGreen: UIColor? { get }
    var backgroundTeal: UIColor? { get }
    var backgroundTealSubtle0: UIColor? { get }
    var backgroundTealSubtle1: UIColor? { get }
    var backgroundBlue: UIColor? { get }
    var backgroundPurple: UIColor? { get }
    var backgroundFuchsia: UIColor? { get }
    var backgroundRed: UIColor? { get }
    var backgroundYellowOrange: UIColor? { get }
    var backgroundVault: UIColor? { get }
    var backgroundVaultGradient0: UIColor? { get }
    var backgroundVaultGradient5: UIColor? { get }
    var backgroundVaultGradient10: UIColor? { get }
    var backgroundVaultSubtle0: UIColor? { get }
    var backgroundVaultSubtle1: UIColor? { get }
    var backgroundSelectSubtle0: UIColor? { get }
    var backgroundSelectSubtle1: UIColor? { get }
    var backgroundMatchExpiration0: UIColor? { get }
    var backgroundMatchExpiration1: UIColor? { get }
    var backgroundExploreAttribution0: UIColor? { get }
    var backgroundExploreAttribution1: UIColor? { get }
    var backgroundFestivalMode0: UIColor? { get }
    var backgroundFestivalMode1: UIColor? { get }
    var backgroundHotTakes0: UIColor? { get }
    var backgroundHotTakes1: UIColor? { get }
    var backgroundSpotifyMusicMode0: UIColor? { get }
    var backgroundSpotifyMusicMode1: UIColor? { get }
    var backgroundCardDefault: UIColor? { get }
    var backgroundCardSparks: UIColor? { get }
    var backgroundMenuDefault: UIColor? { get }
    var backgroundHeaderSparks: UIColor? { get }
    var backgroundRippleDefault: UIColor? { get }
    var backgroundSparksPrimary0: UIColor? { get }
    var backgroundSparksPrimary1: UIColor? { get }
    var backgroundSparksProfile: UIColor? { get }
    var backgroundSparksTopNav: UIColor? { get }
    var backgroundSparksBottomNav: UIColor? { get }
    var backgroundSparksLike0: UIColor? { get }
    var backgroundSparksLike1: UIColor? { get }
    var backgroundSparksNope0: UIColor? { get }
    var backgroundSparksNope1: UIColor? { get }
    var backgroundSparksSuperLike0: UIColor? { get }
    var backgroundSparksSuperLike1: UIColor? { get }
    var backgroundSparksBoost0: UIColor? { get }
    var backgroundSparksBoost1: UIColor? { get }
    var backgroundSparksRewind0: UIColor? { get }
    var backgroundSparksRewind1: UIColor? { get }
    var backgroundSparksPrompt: UIColor? { get }
    var backgroundTrust: UIColor? { get }
    var borderPrimary: UIColor? { get }
    var borderPrimaryInverse: UIColor? { get }
    var borderSecondary: UIColor? { get }
    var borderSecondaryOverlay: UIColor? { get }
    var borderDisabled: UIColor? { get }
    var borderOverlay: UIColor? { get }
    var borderBrand: UIColor? { get }
    var borderBrandGradient0: UIColor? { get }
    var borderBrandGradient1: UIColor? { get }
    var borderGold: UIColor? { get }
    var borderPlatinum: UIColor? { get }
    var borderRewind: UIColor? { get }
    var borderLike: UIColor? { get }
    var borderSuperLike: UIColor? { get }
    var borderBoost: UIColor? { get }
    var borderNope: UIColor? { get }
    var borderFocusDefault: UIColor? { get }
    var borderFocusOverlay: UIColor? { get }
    var borderFocusInverse: UIColor? { get }
    var borderError: UIColor? { get }
    var borderSuccess: UIColor? { get }
    var borderActive: UIColor? { get }
    var borderContainerElevated: UIColor? { get }
    var borderVault: UIColor? { get }
    var borderVaultGradient0: UIColor? { get }
    var borderVaultGradient5: UIColor? { get }
    var borderVaultGradient10: UIColor? { get }
    var borderMatchExpiration0: UIColor? { get }
    var borderMatchExpiration1: UIColor? { get }
    var borderTimerExpired: UIColor? { get }
    var borderSparksLike: UIColor? { get }
    var borderSparksNope: UIColor? { get }
    var borderSparksSuperLike: UIColor? { get }
    var borderSparksBoost: UIColor? { get }
    var borderSparksRewind: UIColor? { get }
    var borderSparksPromptSelected0: UIColor? { get }
    var borderSparksPromptSelected1: UIColor? { get }
    var cursorDefault: UIColor? { get }
    var deviceHomeIndicator: UIColor? { get }
    var deviceStatusBar: UIColor? { get }
    var deviceStatusBarInverse: UIColor? { get }
    var dividerPrimary: UIColor? { get }
    var dividerSparks: UIColor? { get }
    var foregroundPrimaryStaticOnDark: UIColor? { get }
    var foregroundPrimary: UIColor? { get }
    var foregroundPrimaryInverse: UIColor? { get }
    var foregroundSecondary: UIColor? { get }
    var foregroundSecondaryInverse: UIColor? { get }
    var foregroundInactive: UIColor? { get }
    var foregroundDisabled: UIColor? { get }
    var foregroundPrimaryStaticLight: UIColor? { get }
    var foregroundPrimaryStaticDark: UIColor? { get }
    var foregroundSecondaryStaticLight: UIColor? { get }
    var foregroundSecondaryStaticDark: UIColor? { get }
    var foregroundBorderPrimary: UIColor? { get }
    var foregroundBorderSecondary: UIColor? { get }
    var foregroundBorderElevated: UIColor? { get }
    var foregroundReadReceiptsBadge: UIColor? { get }
    var foregroundGreen: UIColor? { get }
    var foregroundTeal: UIColor? { get }
    var foregroundBlue: UIColor? { get }
    var foregroundPurple: UIColor? { get }
    var foregroundFuchsia: UIColor? { get }
    var foregroundRed: UIColor? { get }
    var foregroundYellowOrange: UIColor? { get }
    var iconPrimary: UIColor? { get }
    var iconSecondary: UIColor? { get }
    var iconPrimaryInverse: UIColor? { get }
    var iconSecondaryInverse: UIColor? { get }
    var iconDisabled: UIColor? { get }
    var iconPrimaryOverlay: UIColor? { get }
    var iconPrimaryOverlayInverse: UIColor? { get }
    var iconBrand: UIColor? { get }
    var iconBrandGradient0: UIColor? { get }
    var iconBrandGradient1: UIColor? { get }
    var iconTrust: UIColor? { get }
    var iconSuccess: UIColor? { get }
    var iconError: UIColor? { get }
    var iconLike0: UIColor? { get }
    var iconLike1: UIColor? { get }
    var iconNope0: UIColor? { get }
    var iconNope1: UIColor? { get }
    var iconSuperlike0: UIColor? { get }
    var iconSuperlike1: UIColor? { get }
    var iconBoost0: UIColor? { get }
    var iconBoost1: UIColor? { get }
    var iconRewind0: UIColor? { get }
    var iconRewind1: UIColor? { get }
    var iconGold0: UIColor? { get }
    var iconGold1: UIColor? { get }
    var iconPlatinum0: UIColor? { get }
    var iconPlatinum1: UIColor? { get }
    var iconChatHeartDefault: UIColor? { get }
    var iconChatHeartActive: UIColor? { get }
    var iconChatDrawerContactCardDefault: UIColor? { get }
    var iconChatDrawerContactCardActive: UIColor? { get }
    var iconChatDrawerGifForegroundDefault: UIColor? { get }
    var iconChatDrawerGifBackgroundDefault: UIColor? { get }
    var iconChatDrawerGifForegroundActive: UIColor? { get }
    var iconChatDrawerGifBackgroundActive: UIColor? { get }
    var iconChatDrawerStickerDefault: UIColor? { get }
    var iconChatDrawerStickerActive: UIColor? { get }
    var iconChatDrawerSpotifyForegroundDefault: UIColor? { get }
    var iconChatDrawerSpotifyBackgroundDefault: UIColor? { get }
    var iconChatDrawerSpotifyForegroundActive: UIColor? { get }
    var iconChatDrawerSpotifyBackgroundActive: UIColor? { get }
    var iconChatDrawerNoonlightForegroundDefault: UIColor? { get }
    var iconChatDrawerNoonlightBackgroundDefault: UIColor? { get }
    var iconChatDrawerNoonlightForegroundActive: UIColor? { get }
    var iconChatDrawerNoonlightBackgroundActive: UIColor? { get }
    var iconChatDrawerVibesDefault: UIColor? { get }
    var iconChatDrawerVibesActive0: UIColor? { get }
    var iconChatDrawerVibesActive5: UIColor? { get }
    var iconChatDrawerVibesActive10: UIColor? { get }
    var iconVault: UIColor? { get }
    var iconVaultGradient0: UIColor? { get }
    var iconVaultGradient5: UIColor? { get }
    var iconVaultGradient10: UIColor? { get }
    var iconMatchExpiration0: UIColor? { get }
    var iconMatchExpiration1: UIColor? { get }
    var iconSparksLike0: UIColor? { get }
    var iconSparksLike1: UIColor? { get }
    var iconSparksNope0: UIColor? { get }
    var iconSparksNope1: UIColor? { get }
    var iconSparksSuperLike0: UIColor? { get }
    var iconSparksSuperLike1: UIColor? { get }
    var iconSparksBoost0: UIColor? { get }
    var iconSparksBoost1: UIColor? { get }
    var iconSparksRewind0: UIColor? { get }
    var iconSparksRewind1: UIColor? { get }
    var iconSparksMatchmakerAttribution0: UIColor? { get }
    var iconSparksMatchmakerAttribution1: UIColor? { get }
    var interactivePrimary: UIColor? { get }
    var interactiveSecondary: UIColor? { get }
    var interactiveOnLight: UIColor? { get }
    var loaderShimmerBaseDefault: UIColor? { get }
    var loaderShimmerHighlightDefault: UIColor? { get }
    var loaderSkeleton: UIColor? { get }
    var overlayDefault: UIColor? { get }
    var overlayPrimaryGradient0: UIColor? { get }
    var overlayPrimaryGradient1: UIColor? { get }
    var overlaySecondaryGradient0: UIColor? { get }
    var overlaySecondaryGradient1: UIColor? { get }
    var overlayProfileButtonGamepad0: UIColor? { get }
    var overlayProfileButtonGamepad1: UIColor? { get }
    var overlayProfileSparksSuperLike0: UIColor? { get }
    var overlayProfileSparksSuperLike25: UIColor? { get }
    var overlayProfileSparksSuperLike50: UIColor? { get }
    var overlayProfileSparksSuperLike75: UIColor? { get }
    var overlayProfileSparksSuperLike100: UIColor? { get }
    var shadowContainerElevated: UIColor? { get }
    var shimmerGold0: UIColor? { get }
    var shimmerGold125: UIColor? { get }
    var shimmerGold250: UIColor? { get }
    var shimmerGold375: UIColor? { get }
    var shimmerGold500: UIColor? { get }
    var shimmerGold625: UIColor? { get }
    var shimmerGold750: UIColor? { get }
    var shimmerGold875: UIColor? { get }
    var shimmerGold1000: UIColor? { get }
    var shimmerPlatinum0: UIColor? { get }
    var shimmerPlatinum125: UIColor? { get }
    var shimmerPlatinum250: UIColor? { get }
    var shimmerPlatinum375: UIColor? { get }
    var shimmerPlatinum500: UIColor? { get }
    var shimmerPlatinum625: UIColor? { get }
    var shimmerPlatinum750: UIColor? { get }
    var shimmerPlatinum875: UIColor? { get }
    var shimmerPlatinum1000: UIColor? { get }
    var textPrimary: UIColor? { get }
    var textPrimaryInverse: UIColor? { get }
    var textSecondary: UIColor? { get }
    var textSecondaryInverse: UIColor? { get }
    var textInactive: UIColor? { get }
    var textPrimaryOverlay: UIColor? { get }
    var textPrimaryOverlayInverse: UIColor? { get }
    var textSecondaryOverlay: UIColor? { get }
    var textSecondaryOverlayInverse: UIColor? { get }
    var textError: UIColor? { get }
    var textLink: UIColor? { get }
    var textGold: UIColor? { get }
    var textLike: UIColor? { get }
    var textSuperLike: UIColor? { get }
    var textBoost: UIColor? { get }
    var textSuperBoost: UIColor? { get }
    var textSuccess: UIColor? { get }
    var textDisabled: UIColor? { get }
    var textLinkOverlay: UIColor? { get }
    var textHighlightForeground: UIColor? { get }
    var textHighlightBackground: UIColor? { get }
    var textBrandNormal: UIColor? { get }
    var textBrandLarge: UIColor? { get }
    var textVaultNormal: UIColor? { get }
    var textVaultLarge: UIColor? { get }
    var textMatchExpiration0: UIColor? { get }
    var textMatchExpiration1: UIColor? { get }
    var textTrust: UIColor? { get }
    var textSparksMatchmakerAttribution0: UIColor? { get }
    var textSparksMatchmakerAttribution1: UIColor? { get }
    var fadePrimaryBottomToTop0: UIColor? { get }
    var fadePrimaryBottomToTop1: UIColor? { get }
    var fadePrimaryTopToBottom0: UIColor? { get }
    var fadePrimaryTopToBottom1: UIColor? { get }
    init()
}
